from .normal import NormalNormal_MuPrior1D, MultivariateNormalNormal_MuPrior, NormalNormal_NormalInverseGammaPrior1D
from .bernoulli import BernoulliBeta_PPrior
from .categorical import CategoricalDirichlet_PPrior
from .exponential import ExponentialGamma_LambdaPrior
from .binomial import BinomialBeta_PPrior
from .multinomial import MultinomialDirichlet_PPrior
