from .normal import MultiVariateNormal as multivariate_normal
from .normal import Normal as normal
from .uniform import MultiVariateUniform as multivariate_uniform
from .uniform import Uniform as uniform
from .bernoulli import Bernoulli as bernoulli
from .categorical import Categorical as categorical
from .dirichlet import Dirichlet as dirichlet
from .beta import Beta as beta
from .exponential import Exponential as exponential
